services:
  ####### Node Exporter #######
  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring_node_exporter
    restart: unless-stopped
    networks:
      grafana:
    expose:
      - 9100
  ####### Prometheus #######
  prometheus:
    restart: unless-stopped
    user: root
    image: prom/prometheus:v2.48.1
    volumes:
      - ./data/prometheus:/prometheus
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      grafana:
  ####### Graphana #######
  grafana:
    restart: unless-stopped
    user: "1000:1000" # you may need to change this by using id -u
    image: grafana/grafana:10.2.2
    networks:
      grafana:
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      GF_SMTP_HOST: maildev:1025
      GF_METRICS_INTERVAL_SECONDS: 5
      GF_ALERTING_MIN_INTERVAL_SECONDS: 5
      GF_ALERTING_MAX_ATTEMPTS: 1
      GF_SMTP_ENABLED: "true"
    ports:
      - 3000:3000
  promtail:
    image: grafana/promtail
    networks:
      grafana:
    volumes:
      - ./config/loki:/mnt/config
      - ./data/zeek/logs:/zeek-logs
      - ./data/suricata/logs:/suricata-logs
    command: -config.file=/mnt/config/promtail-config.yml
  loki:
    image: grafana/loki
    volumes:
      - "./config/loki:/mnt/config"
    networks:
      grafana:
    command: "-config.file=/mnt/config/loki-config.yml"

  ####### Zeek  #######
  zeek:
    image: zeek/zeek:lts
    network_mode: host
    volumes:
      - ./data/zeek/logs:/logs
    command: /bin/bash -c "cd /logs && zeek -i any"
  ####### Suricata #######
  suricata:
    build:
      context: suricata/.
    network_mode: host
    volumes:
      - ./config/suricata/suricata.yml:/etc/suricata/suricata.yml
      - ./data/suricata/rules:/var/lib/suricata/rules
      - ./data/suricata/logs:/var/log/suricata/
    # change wlp3s0 by result of ip addr
    command: /bin/bash -c "suricata-update && suricata -c /etc/suricata/suricata.yaml -i br_grafana && tail -f /var/log/cron.log"
  ####### Maildev #######
  maildev:
    image: maildev/maildev
    restart: always
    networks:
      grafana:
    environment:
      - TZ=Europe/Paris
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "1080:1080"
  ####### Apps #######
  server-app:
    build:
      context: ./server-app/.
    networks:
      grafana:
    ports:
      - "3001:80"
    environment:
      RESET_ACESS_METRIC: "900000" # 10 minutes
  stress:
    build:
      context: ./stress/.
  curl:
    networks:
      grafana:
    build:
      context: ./curl/.
networks:
  grafana:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
    driver_opts:
      com.docker.network.bridge.name: br_grafana
