services:
  ####### Node Exporter #######
  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring_node_exporter
    restart: unless-stopped
    networks:
      grafana:
    expose:
      - 9100
  ####### Prometheus #######
  prometheus:
    restart: unless-stopped
    user: "1000:1000" # you may need to change this by using id -u
    image: prom/prometheus:v2.48.1
    volumes:
      - ./data/prometheus:/prometheus
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      grafana:
  ####### Graphana #######
  grafana:
    restart: unless-stopped
    user: "1000:1000" # you may need to change this by using id -u
    image: grafana/grafana:10.2.2
    networks:
      grafana:
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      GF_SMTP_HOST: maildev:1025
      GF_SMTP_ENABLED: "true"
    ports:
      - 3000:3000
  ####### Maildev #######
  maildev:
    image: maildev/maildev
    restart: always
    networks:
      grafana:
    environment:
      - TZ=Europe/Paris
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "1080:1080"

  server-app:
    build:
      context: server-app/.
    networks:
      grafana:
    ports:
      - "3001:80"
networks:
  grafana:
