global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: "server_app"
    static_configs:
      - targets: ["server-app:80"]
